const router = require('express').Router();
const menu = require('../controllers/menu/menu.controller');
const authenticate = require('../middlewares/auth.middleware');
const roles = require('../middlewares/authorize.middleware');
const scope = require('../middlewares/restaurant-scope.middleware');
const upload = require('../middlewares/upload.middleware');
const admin = [authenticate, roles('super_admin', 'restaurant_admin'), scope];
router.get('/', scope, menu.list);
router.get('/:id', scope, menu.get);
router.post('/', ...admin, upload.single('image'), menu.create);
router.patch('/:id', ...admin, upload.single('image'), menu.update);
router.delete('/:id', ...admin, menu.remove);
module.exports = router;
