const router = require('express').Router();
const authenticate = require('../middlewares/authMiddleware');
const roles = require('../middlewares/roleMiddleware');
const scope = require('../middlewares/restaurantScope');
router.use(authenticate);
router.post('/', roles('user'), require('../controllers/orderController').placeOrder);
router.get('/', roles('super_admin', 'restaurant_admin', 'kitchen'), scope, require('../controllers/AdminMenuController'));
router.get('/:id', roles('user'), require('../controllers/OrderStatusController'));
router.patch('/:id', roles('super_admin', 'restaurant_admin', 'kitchen'), scope, require('../controllers/AdminMenuStatusUpdate'));
module.exports = router;
