-- Local demo data only. Run once after schema.sql. Adds a new restaurant.
-- All sample accounts use DemoOnly@123. Never use these accounts in production.
USE restaurant_db;
START TRANSACTION;
INSERT INTO roles (role_id,name,description) SELECT COALESCE(MAX(role_id),0)+1, 'admin', 'Demo admin role' FROM roles HAVING SUM(name = 'admin') IS NULL OR SUM(name = 'admin') = 0;
SET @role_admin = (SELECT role_id FROM roles WHERE name = 'admin');
INSERT INTO roles (role_id,name,description) SELECT COALESCE(MAX(role_id),0)+1, 'manager', 'Demo manager role' FROM roles HAVING SUM(name = 'manager') IS NULL OR SUM(name = 'manager') = 0;
SET @role_manager = (SELECT role_id FROM roles WHERE name = 'manager');
INSERT INTO roles (role_id,name,description) SELECT COALESCE(MAX(role_id),0)+1, 'staff', 'Demo staff role' FROM roles HAVING SUM(name = 'staff') IS NULL OR SUM(name = 'staff') = 0;
SET @role_staff = (SELECT role_id FROM roles WHERE name = 'staff');
INSERT INTO roles (role_id,name,description) SELECT COALESCE(MAX(role_id),0)+1, 'users', 'Demo users role' FROM roles HAVING SUM(name = 'users') IS NULL OR SUM(name = 'users') = 0;
SET @role_users = (SELECT role_id FROM roles WHERE name = 'users');
INSERT INTO restaurants (name) VALUES ('Sample Garden Restaurant');
SET @restaurant = LAST_INSERT_ID();
INSERT INTO users (username,email,password,mob_no,restaurant_id,role_id,isActive) VALUES ('Demo admin', 'demo.admin@example.test', '$2b$12$7R/CnFdNL.QWBcqSVHHplehjOFx6fr/njLSltyS8PIvXuLSaPZVwu', '9900000001', NULL, @role_admin, 1);
SET @user_admin = LAST_INSERT_ID();
INSERT INTO users (username,email,password,mob_no,restaurant_id,role_id,isActive) VALUES ('Demo manager', 'demo.manager@example.test', '$2b$12$7R/CnFdNL.QWBcqSVHHplehjOFx6fr/njLSltyS8PIvXuLSaPZVwu', '9900000002', @restaurant, @role_manager, 1);
SET @user_manager = LAST_INSERT_ID();
INSERT INTO users (username,email,password,mob_no,restaurant_id,role_id,isActive) VALUES ('Demo staff', 'demo.staff@example.test', '$2b$12$7R/CnFdNL.QWBcqSVHHplehjOFx6fr/njLSltyS8PIvXuLSaPZVwu', '9900000003', @restaurant, @role_staff, 1);
SET @user_staff = LAST_INSERT_ID();
INSERT INTO users (username,email,password,mob_no,restaurant_id,role_id,isActive) VALUES ('Demo users', 'demo.users@example.test', '$2b$12$7R/CnFdNL.QWBcqSVHHplehjOFx6fr/njLSltyS8PIvXuLSaPZVwu', '9900000004', NULL, @role_users, 1);
SET @user_users = LAST_INSERT_ID();
INSERT INTO categories (c_name,description,restaurant_id) VALUES ('Demo Main Courses','Sample dishes',@restaurant);
SET @category = LAST_INSERT_ID();
INSERT INTO menu (name,descriptions,price,discount,category_id,restaurant_id) VALUES ('Demo Vegetable Pizza','Sample menu item',249,0,@category,@restaurant);
SET @product = LAST_INSERT_ID();
INSERT INTO menu (name,descriptions,price,discount,category_id,restaurant_id) VALUES ('Demo Pasta','Sample menu item',199,0,@category,@restaurant);
INSERT INTO restaurant_home (restaurant_id,hero_title,hero_image_url,description,opening_hours,sections) VALUES (@restaurant,'Welcome to Sample Garden','/images/restaurant.jpg','Demo restaurant content. Replace before publishing.','Demo hours: 11:00?22:00',JSON_ARRAY(JSON_OBJECT('title','About us','description','A sample restaurant for testing the application.')));
INSERT INTO restaurant_info (restaurant_name,address,phone,email,description,cover_image_url,opening_time,closing_time) VALUES ('Sample Garden Restaurant','Demo address ? replace before publishing','9900000099','restaurant@example.test','Legacy sample profile','/images/restaurant.jpg','11:00:00','22:00:00');
INSERT INTO gallery (image_url,caption) VALUES ('/images/restaurant.jpg','Demo restaurant image');
INSERT INTO table_reservation (user_id,customer_name,customer_phone,number_of_persons,reservation_date,reservation_time,table_no,status,restaurant_id) VALUES (@user_users,'Demo Customer','9900000004',2,DATE_ADD(CURDATE(),INTERVAL 1 DAY),'19:00:00','D1','confirmed',@restaurant);
INSERT INTO invoice (customer_id,invoice_date,total_amount,notes,order_status,payment_status,restaurant_id) VALUES (@user_users,CURDATE(),249,'Demo order','pending','unpaid',@restaurant);
SET @invoice = LAST_INSERT_ID();
INSERT INTO invoice_item (invoice_id,product_id,quantity,unit_price,line_total) VALUES (@invoice,@product,1,249,249);
INSERT INTO invoice (customer_id,invoice_date,total_amount,notes,order_status,payment_status,restaurant_id) VALUES (@user_users,CURDATE(),249,'Demo order','accepted','unpaid',@restaurant);
SET @invoice = LAST_INSERT_ID();
INSERT INTO invoice_item (invoice_id,product_id,quantity,unit_price,line_total) VALUES (@invoice,@product,1,249,249);
INSERT INTO invoice (customer_id,invoice_date,total_amount,notes,order_status,payment_status,restaurant_id) VALUES (@user_users,CURDATE(),249,'Demo order','preparing','unpaid',@restaurant);
SET @invoice = LAST_INSERT_ID();
INSERT INTO invoice_item (invoice_id,product_id,quantity,unit_price,line_total) VALUES (@invoice,@product,1,249,249);
INSERT INTO invoice (customer_id,invoice_date,total_amount,notes,order_status,payment_status,restaurant_id) VALUES (@user_users,CURDATE(),249,'Demo order','completed','unpaid',@restaurant);
SET @invoice = LAST_INSERT_ID();
INSERT INTO invoice_item (invoice_id,product_id,quantity,unit_price,line_total) VALUES (@invoice,@product,1,249,249);
INSERT INTO invoice (customer_id,invoice_date,total_amount,notes,order_status,payment_status,restaurant_id) VALUES (@user_users,CURDATE(),249,'Demo order','delivered','paid',@restaurant);
SET @invoice = LAST_INSERT_ID();
INSERT INTO invoice_item (invoice_id,product_id,quantity,unit_price,line_total) VALUES (@invoice,@product,1,249,249);
INSERT INTO payment (invoice_id,customer_id,payment_date,amount,method,reference_number) VALUES (@invoice,@user_users,CURDATE(),249,'cash','DEMO-CASH');
COMMIT;
SELECT @restaurant AS sample_restaurant_id;
