require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const validate = require('./middlewares/validate.middleware');
const app = express();
app.use(cors({ origin: '*', methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'], credentials: true }));
app.use(express.json());
app.use(validate.body);
app.use('/uploads', express.static(path.join(__dirname, '..', 'uploads')));
app.use('/api/v1', validate.resourceId, require('./routes'));
app.use((req, res) => res.status(404).json({ message: 'Path does not exist' }));
app.use(require('./middlewares/error.middleware'));
module.exports = app;
